ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
  hosts:
  - host: test.example.com
    paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: release-name
          port:
            number: 80

autoscaling:
  enabled: true

service:
  type: ClusterIP
  httpPort: 80
  targetPort: 8080

replicaCount: 2

image:
  url: 534420079206.dkr.ecr.ap-northeast-2.amazonaws.com/backend-app:latest
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "subnet_type"
              operator: In
              values:
                - "private"

minReadySeconds: 10

revisionHistoryLimit: 2

terminationMessagePath: /dev/termination-log

terminationMessagePolicy: File

dnsPolicy: ClusterFirst

restartPolicy: Always

schedulerName: default-scheduler

terminationGracePeriodSeconds: 30
