ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
  hosts: []
  
autoscaling:
  enabled: false

service:
  type: ClusterIP
  httpPort: 80
  targetPort: 8080

replicaCount: 2

image:
  url: {}
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

tolerations: []

affinity: {}

minReadySeconds: 10

revisionHistoryLimit: 2

terminationMessagePath: /dev/termination-log

terminationMessagePolicy: File

dnsPolicy: ClusterFirst

restartPolicy: Always

schedulerName: default-scheduler

terminationGracePeriodSeconds: 30
